const customersLogos = [
	"images/customers/01.webp",
	"images/customers/02.webp",
	"images/customers/03.webp",
	"images/customers/04.webp",
	"images/customers/05.webp",
	"images/customers/06.webp",
	"images/customers/07.webp",
	"images/customers/08.webp",
	"images/customers/09.webp",
	"images/customers/10.webp",
	"images/customers/11.webp",
	"images/customers/12.webp",
	"images/customers/13.webp",
	"images/customers/14.webp",
	"images/customers/15.webp",
	"images/customers/16.webp",
	"images/customers/17.webp",
	"images/customers/18.webp",
	"images/customers/19.webp",
	"images/customers/20.webp",
	"images/customers/21.webp",
	"images/customers/22.webp",
	"images/customers/23.webp",
	"images/customers/24.webp",
	"images/customers/25.webp",
	"images/customers/26.webp",
	"images/customers/27.webp",
	"images/customers/28.webp",
];

export {customersLogos};